name: Android build
on:
  workflow_call:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodules
        uses: ./.github/actions/submodules

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
          link-to-sdk: true

      - name: Compile
        run: python build.py platform=android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pixelpart-android
          path: |
            ./net.pixelpart.core/Runtime/Plugins/Android/arm32/libpixelpart.so
            ./net.pixelpart.core/Runtime/Plugins/Android/arm64/libpixelpart.so
            ./net.pixelpart.core/Runtime/Plugins/Android/x86/libpixelpart.so
            ./net.pixelpart.core/Runtime/Plugins/Android/x86_64/libpixelpart.so