name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  windows-build:
    name: Windows build
    uses: ./.github/workflows/windows_build.yml

  linux-build:
    name: Linux build
    uses: ./.github/workflows/linux_build.yml

  macos-build:
    name: macOS build
    uses: ./.github/workflows/macos_build.yml

  webgl-2-0-19-build:
    name: WebGL Emscripten 2.0.19 build
    uses: ./.github/workflows/webgl_2_0_19_build.yml

  webgl-3-1-8-build:
    name: WebGL Emscripten 3.1.8 build
    uses: ./.github/workflows/webgl_3_1_8_build.yml

  webgl-3-1-38-build:
    name: WebGL Emscripten 3.1.38 build
    uses: ./.github/workflows/webgl_3_1_38_build.yml

  package:
    name: Package plugin
    runs-on: ubuntu-latest
    needs: [windows-build, linux-build, macos-build, webgl-2-0-19-build, webgl-3-1-8-build, webgl-3-1-38-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-windows
          path: artifacts/windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-linux
          path: artifacts/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-macos
          path: artifacts/macos

      - name: Download WebGL 2.0.19 artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-webgl-2-0-19
          path: artifacts/webgl-2-0-19

      - name: Download WebGL 3.1.8 artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-webgl-3-1-8
          path: artifacts/webgl-3-1-8

      - name: Download WebGL 3.1.38 artifacts
        uses: actions/download-artifact@v4
        with:
          name: pixelpart-webgl-3-1-38
          path: artifacts/webgl-3-1-38

      - name: Display downloaded artifacts
        run: ls -R artifacts

      - name: Copy binaries
        run: |
          cp artifacts/windows/x86/pixelpart.dll ./net.pixelpart.core/Runtime/Plugins/x86/
          cp artifacts/windows/x86_64/pixelpart.dll ./net.pixelpart.core/Runtime/Plugins/x86_64/
          cp artifacts/linux/x86/libpixelpart.so ./net.pixelpart.core/Runtime/Plugins/x86/
          cp artifacts/linux/x86_64/libpixelpart.so ./net.pixelpart.core/Runtime/Plugins/x86_64/
          cp artifacts/macos/pixelpart.bundle ./net.pixelpart.core/Runtime/Plugins/macOS/
          cp -r artifacts/webgl-2-0-19/* ./net.pixelpart.core/Runtime/Plugins/WebGL/2.0.19/
          cp -r artifacts/webgl-3-1-8/* ./net.pixelpart.core/Runtime/Plugins/WebGL/3.1.8/
          cp -r artifacts/webgl-3-1-38/* ./net.pixelpart.core/Runtime/Plugins/WebGL/3.1.38/

      - name: Create Unity packages
        run: |
          python package.py -o net.pixelpart.core.tgz -t net.pixelpart.core
          python package.py -o net.pixelpart.urp.tgz -t net.pixelpart.urp
          python package.py -o net.pixelpart.hdrp.tgz -t net.pixelpart.hdrp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pixelpart-plugin-unity
          path: |
            net.pixelpart.core.tgz
            net.pixelpart.urp.tgz
            net.pixelpart.hdrp.tgz