name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  windows-build:
    name: Windows build
    uses: ./.github/workflows/windows_build.yml

  linux-build:
    name: Linux build
    uses: ./.github/workflows/linux_build.yml

  macos-build:
    name: macOS build
    uses: ./.github/workflows/macos_build.yml

  web-build:
    name: Web build
    uses: ./.github/workflows/web_build.yml

  package:
    name: Package plugin
    runs-on: ubuntu-20.04
    needs: [windows-build, linux-build, macos-build, web-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64

      - name: Setup PyYAML
        run: python -m pip install PyYAML

      - name: Download Windows artifacts
        uses: actions/download-artifact@v1
        with:
          name: pixelpart-windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v1
        with:
          name: pixelpart-linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v1
        with:
          name: pixelpart-macos

      - name: Download web artifacts
        uses: actions/download-artifact@v1
        with:
          name: pixelpart-web

      - name: Copy binaries
        run: |
          cp pixelpart-windows/x86/pixelpart.dll ./pixelpart-plugin/Assets/Pixelpart/Plugins/x86/
          cp pixelpart-windows/x86_64/pixelpart.dll ./pixelpart-plugin/Assets/Pixelpart/Plugins/x86_64/
          cp pixelpart-linux/x86/libpixelpart.so ./pixelpart-plugin/Assets/Pixelpart/Plugins/x86/
          cp pixelpart-linux/x86_64/libpixelpart.so ./pixelpart-plugin/Assets/Pixelpart/Plugins/x86_64/
          cp pixelpart-macos/pixelpart.bundle ./pixelpart-plugin/Assets/Pixelpart/Plugins/macOS/
          cp -r pixelpart-web/* ./pixelpart-plugin/Assets/Pixelpart/Plugins/WebGL/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pixelpart-plugin-unity-assets
          path: ./pixelpart-plugin/Assets

      - name: Create Unity package
        run: |
          cd pixelpart-plugin
          python ../package.py -o ../pixelpart-plugin-unity.unitypackage Assets/Pixelpart Assets/Gizmos

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: pixelpart-plugin-unity
          path: pixelpart-plugin-unity.unitypackage