name: iOS build
on:
  workflow_call:

jobs:
  build-ios:
    runs-on: macOS-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodules
        uses: ./.github/actions/submodules

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Compile
        run: python build.py platform=ios

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pixelpart-ios
          path: |
            ./net.pixelpart.core/Runtime/Plugins/iOS/libpixelpart.a