name: Web build
on:
  workflow_call:

jobs:
  build-web:
    runs-on: ubuntu-20.04
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodules
        uses: ./.github/actions/submodules

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Compile
        run: python build.py platform=web

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pixelpart-web
          path: ./pixelpart-plugin/Assets/Pixelpart/Plugins/WebGL