name: WebGL Emscripten 3.1.8 build
on:
  workflow_call:

jobs:
  build-webgl-3-1-8:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update submodules
        uses: ./.github/actions/submodules

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Cache emsdk
        id: cache
        uses: actions/cache@v4
        with:
          path: ./emsdk
          key: ${{ runner.os }}-emsdk-3_1_8

      - name: Install emsdk
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install 3.1.8

      - name: Compile
        run: |
          ./emsdk/emsdk activate 3.1.8
          source ./emsdk/emsdk_env.sh
          python build.py platform=web
          cp ./net.pixelpart.core/Runtime/Plugins/WebGL/libpixelpart.a ./net.pixelpart.core/Runtime/Plugins/WebGL/3.1.8/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pixelpart-webgl-3-1-8
          path: ./net.pixelpart.core/Runtime/Plugins/WebGL/3.1.8